name: JetBrains Test
on:
  workflow_dispatch:
    inputs:
      secret_gateway_link:
        type: string
        description: Gateway Link
        required: true
      secret_access_token:
        type: string
        description: OAuth2 Access Token
        required: true
      secret_endpoint:
        type: string
        description: IDE Endpoint
        required: true
jobs:
  jetbrains-smoke-test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: "11"
      # - name: Auth Google Cloud SDK
      #   uses: google-github-actions/auth@v0
      #   with:
      #     credentials_json: ${{ secrets.serviceAccountKey }}
      # - name: Setup Google
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     project_id: ${{ secrets.projectId }}
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Gateway Plugin
        working-directory: components/ide/jetbrains/gateway-plugin
        run: |
          ./gradlew -PpluginVersion=test buildPlugin
      - name: Smoke Test
        env:
          LEEWAY_REMOTE_CACHE_BUCKET: gitpod-core-leeway-cache-branch
        working-directory: dev/jetbrains-test
        run: |
          mkdir ./build && cp -r ../../components/ide/jetbrains/gateway-plugin/build/distributions/gitpod-gateway-test.zip build/gateway-test.zip

          export GATEWAY_LINK=$(jq -r '.inputs.secret_gateway_link' $GITHUB_EVENT_PATH)
          export GITPOD_TEST_ACCESSTOKEN=$(jq -r '.inputs.secret_access_token' $GITHUB_EVENT_PATH)
          export WS_ENDPOINT=$(jq -r '.inputs.secret_endpoint' $GITHUB_EVENT_PATH)
          export GATEWAY_PLUGIN_PATH=$(pwd)/build/gateway-test.zip

          echo "$WS_ENDPOINT ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCybpjrskn0GkkjkxgT/OK108wu1UkCkWVkuvA+TEMtjnyNvwPs7PJZwk1N1Isk7F40/1eF3luTixDcvzTn4R6AAWG2/DRbDJTUoy9bV2MH84bB64SMBLYwRUj60e8zF1GFGtQxolrIO75M61qqAM1vCkpEAuLszKIC7xKkYNIVI1sDXAZDrRjn5MdtFSRpeTCN7mt6EvZVtZKPgzUkSiA507w0IxexSX8OEz1UxidMoTagS8wK+U+VaMWJja6bQ6jqzZ7Ou/uCz0Q99q7hFs0cdAh5Q2KNDG518PB750FoUIxWBsniHtRMh2YLtkrYdHhjRVsmg3ltG78hM3iISCbro4avUo3d7IKL97mLAETKxvAwUTn5pcNzk8jSqo51RlmxWHMgE++xNUeuUirhXTzQHSlCcbKsNcdP9gc2jMOQPAiRmHtzLIuHGGwS85M146PsFy6DG/XZOhu9/DhGVMq51NDKs3X8JHzXVGWxmZqLfM9BM+rojvepZgUa5S1mdwE=" >> ~/.ssh/known_hosts
          echo "$WS_ENDPOINT ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMaWYf9zrhI79dA9iBi7qF1anYtUCdT9l0xG2w9oNKHezKuSrJb+pFbHPsL/HuBHK8Yx1HJEufE4uIv//WGCOlCIdW4D40aKhEu5WXtpo8zI0SxkuOvaWDRuUbYNb3/oNNo79WNuhXR6mWn5skm6D+J5vv8H7V5tYrsZf6UqYZF5uLkeQFsis0UVm3+jNFVY/PuHbo6ndrh9DFCQF4YhMQpGTAG0PLal4VLJ4L31TOnb3buBtCWcf3CslT8IiqREdFcJE6MjaMVMCgENQHRWQ57vjv0xKxoI/sA1tMMzD8KrZxC+yB7Qwiby/8iAuhb1Zluh8sxH0NBv8fh1zI8rxbwP5pG3MnTxsCKYpBN01hyuFWtruARfrEGtSMZ4z5oMAFl08BuXSq+e1Ty/dEjfxv2EuG6enU0EJezqJLeCLWqVPZw7hncJD74J4H2pHlk9v3/q9EAD83GY++IChChBLK6wQybEVk+Md7n9GxjCiDAowspSTnq5FHPuKRjDpc1s8=" >> ~/.ssh/known_hosts
          mkdir -p ~/Library/Application\ Support/JetBrains/consentOptions
          echo -n "rsch.send.usage.stat:1.1:0:1644945193441" > ~/Library/Application\ Support/JetBrains/consentOptions/accepted
          mkdir -p ~/Library/Application\ Support/JetBrains/JetBrainsClient/options
          touch ~/Library/Application\ Support/JetBrains/JetBrainsClient/options/ide.general.xml
          gradle :test
      - name: Move video
        if: always()
        run: |
          cp -r dev/jetbrains-test/video dev/jetbrains-test/build/reports
      - name: Save report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: |
            dev/jetbrains-test/build/reports